### ISSUE TITLE
Component for TokenAmount

### ISSUE THREAD

**Issue by joeldavidw** [BirthdayResearch/defiscan.live#1082]
#### What would you like to be added:
Currently, we are showing full 8 dps for all token amounts (except when token amount is in tens of thousands/millions). When amount is truncated (not full 8 dp) we should implement a hover over functionality which will display the full amount in a popup.

We should have a component that builds on top of `NumberFormat` and `HoverPopover`. 

#### Why is this needed:
To standardise the display format of token amount.

/triage accepted
/area ui-ux core

**Comment by nichellekoh** [comment]
@Graciaho @ngyingzhong to decide on displaying such values
