### ISSUE TITLE
Proper fixes for `/dex` page

### ISSUE THREAD

**Issue by joeldavidw** [BirthdayResearch/defiscan.live#1317]
#### What would you like to be added:
Quick fixes were made in https://github.com/DeFiCh/scan/pull/1316 & #1318.

Proper Fix for the following are needed:
- Filter for splitted pairs (e.g. amzn-dusd/v1)
- Usage of poolpairs `displaySymbol` instead of `tokenA.displaySymbol` for pairs where `tokenA` is used across multiple pairs (dUSDT-DUSD and dUSDT_DFI).

**Comment by joeldavidw** [comment]
May want to consider using full poolpair `displaySymbol` from now on. To prevent links from breaking in the future.

cc: @gjj

**Comment by gjj** [comment]
You mean like the `/v1` in:

* `https://defiscan.live/tokens/dGOOGL/v1`
* `https://defiscan.live/tokens/dGOOGL-dDUSD/v1`
* `https://defiscan.live/tokens/dAMZN/v1`
* ...and all other `v1` stock split symbols?
