### ISSUE TITLE
link to XCHF-DFI opens XCHF-DUSD

### ISSUE THREAD

**Issue by kuegi** [BirthdayResearch/defiscan.live#1867]
#### What happened:

when you click on XCHF-DFI on the dex page, it opens https://defiscan.live/dex/dXCHF which shows XCHF-DUSD

#### What you expected to happen:

it should open https://defiscan.live/dex/dXCHF-DFI

**Comment by pierregee** [comment]
Fixed on https://github.com/BirthdayResearch/defiscan.live/pull/1866
