### ISSUE TITLE
Automatic display of warning message (No blocks minted > 45 mins)

### ISSUE THREAD

**Issue by joeldavidw** [BirthdayResearch/defiscan.live#856]
#### What would you like to be added:
Similar to https://github.com/DeFiCh/wallet/issues/1849. An automatic message should be displayed when there is no new blocks minted for **45 mins**.

**Display Message**

```
We are currently investigating a syncing issue on the blockchain. View more details on the [DeFiChain Status Page](https://status.defichain.com/).
```

Note:
- If possible try explore ways to reuse data that is already stored in the state to reduce number of api calls. It may be possible to use data from stats. However, it may not contain the last block datetime.

/triage accepted
/area ui-ux

**Comment by siradji** [comment]
@joeldavidw ?

**Comment by joeldavidw** [comment]
Let's wait for the status status api to get deployed first. Then we automate this by checking the overall status endpoint.

**Comment by siradji** [comment]
> Let's wait for the status status api to get deployed first. Then we automate this by checking the overall status endpoint.

Make sense

**Comment by thedoublejay** [comment]
Same requirements from LW. Need to do it on Scan also - https://github.com/DeFiCh/wallet/issues/3034
